<?php
namespace Aelia\WC;
if(!defined('ABSPATH')) exit; // Exit if accessed directly

/**
 * Class to represent Admin messages generated by the plugin.
 *
 * @since 1.6.1.150728
 */
class Admin_Message extends Message {
	/**
	 * Class constructor.
	 *
	 * @param int level The message level.
	 * @param string message The message.
	 * @param string code The message code.
	 * @param bool dismissable Indicates if the message can be dismissed.
	 * @param array params Additional parameters for the message.
	 */
	public function __construct($level, $message, $code = '', $dismissable = false, array $params = array()) {
		parent::__construct($level, $message, $code, $dismissable, $params);
	}
}
