name: Deploy | Prodction

on: [push]

jobs:
  build:

    name: Deploy

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USER }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        METHOD: ftp
        PORT: 21
        REMOTE_DIR: test
        ARGS: --verbose --delete --ignore-time --include wp-content/themes/caffewasyl/ --exclude xmlrpc.php --exclude error_log --exclude license.txt --exclude-glob *.ini --exclude-glob wp-* --exclude-glob .git*/ --exclude-glob .git* --exclude wp-content/plugins/* --exclude wp-content/themes/storefront