name: Prodction | Deploy

on: [push]

jobs:
  build:

    name: Deploy

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: PreFTPDeploy
      run: |
        sed 's/^/-X /' .lftp | tr '\n' ' ' > LFTP_EXCLUDES

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USER }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        METHOD: ftp
        PORT: 21
        REMOTE_DIR: test
        ARGS: --delete --ignore-time -X .git*/ -X .git* $(cat LFTP_EXCLUDES) --skip-noaccess --use-cache -v