name: Prodction | Deploy

on: [push]

jobs:
  build:

    name: Deploy

    runs-on: ubuntu-latest

    env:
      LFTP_EXCLUDES: .git

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Pre env Deploy
      run: |
        $LFTP_EXCLUDES = sed 's/^/-X /' .lftp | tr '\n' ' '

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USER }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        METHOD: ftp
        PORT: 21
        REMOTE_DIR: test
        ARGS: --delete --ignore-time -X .git*/ -X .git* ${{ env.LFTP_EXCLUDES }} --skip-noaccess --use-cache -v